import type { Metadata } from "next";
import { DM_Sans, Poppins } from "next/font/google";
import "./globals.css";

const fontBody = DM_Sans({
  subsets: ["latin"],
  variable: "--font-body",
  display: "swap",
});

const fontHeading = Poppins({
  subsets: ["latin"],
  weight: ["500", "600", "700"],
  variable: "--font-heading",
  display: "swap",
});

export const metadata: Metadata = {
  title: "My App",
  description: "Generated by create next app",
  themeColor: "#f9fafb", // ⬅️ PENTING
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="id">
      <body
        className={`${fontBody.variable} ${fontHeading.variable} bg-gray-50 antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
